# Netlify configuration file

[[plugins]]
  # Essential plugin for deploying Next.js sites on Netlify.
  # It automatically configures redirects, serverless functions, and more.
  package = "@netlify/plugin-nextjs" 