[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "next dev -p 3000"
  targetPort = 3000
  port = 8888
  framework = "#custom"
  autoLaunch = false



# Environment variables (set in Netlify dashboard)
# TELEGRAM_BOT_TOKEN=your_bot_token
# TELEGRAM_BOT_USERNAME=your_bot_username  
# TELEGRAM_WEBHOOK_URL=https://your-domain.netlify.app/api/telegram/webhook
# NEXT_PUBLIC_CKB_RPC_URL=https://testnet.ckb.dev
# NEXT_PUBLIC_CKB_INDEXER_URL=https://testnet.ckb.dev/indexer
# NEXT_PUBLIC_SSRI_EXECUTOR_URL=http://localhost:9090